[profile.default]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
libs = ['contracts/lib']
fs_permissions = [{ access = "read", path = "./contracts/out"}, { access = "write", path = "genesis.json"}]
# Docs refs:
# - Uniswap v4 PoolManager lifecycle and hook calls are executed inside v4 core flow:
#   https://docs.uniswap.org/contracts/v4/overview
# - Uniswap v4 hooks concepts:
#   https://docs.uniswap.org/contracts/v4/concepts/hooks
evm_version = "cancun"
offline = true

# For Linux/WSL2 systems, please change to `contracts/lib/v4-core/bin/solc-static-linux`
solc = "contracts/lib/v4-core/bin/solc-mac"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
